In [7]:
mylist=[1,2,3]
print(mylist)

[1, 2, 3]


In [10]:
import numpy as np
ar1=np.array(mylist)

In [11]:
print(ar1)

[1 2 3]


In [13]:
type(ar1)

numpy.ndarray

In [14]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
print(my_mat)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [16]:
ar2=np.array(my_mat)

In [17]:
print(ar2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
#np.arange(start,stop,step)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [30]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.zeros((3,3),(2,4))

TypeError: Cannot interpret '2' as a data type

In [33]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
#np.linspace(start,stop,no.of numbers needed)
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [38]:
#1D=1 brackets,2D=2 brackets,3D=3 brackets


In [40]:
#np.eye(n)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.random.rand(5)

array([0.50452249, 0.17417544, 0.12708787, 0.38879364, 0.06860686])

In [42]:
np.random.rand(3,3)

array([[0.3715611 , 0.99255442, 0.18484223],
       [0.93942563, 0.28033857, 0.67440519],
       [0.84799101, 0.07084638, 0.57093926]])

In [47]:
np.random.randn(4,2)

array([[-0.70308313,  1.21212364],
       [-2.46732202, -0.47285176],
       [ 0.75296274,  1.27981125],
       [-0.27604547, -0.11085895]])

In [48]:
np.random.randn(4)

array([ 0.93166301,  1.71423325, -1.1504645 , -0.85230985])

In [52]:
np.random.randint(1,100,20)

array([82, 52, 77, 49, 60, 66,  4, 49, 48, 55, 15, 76, 16, 11,  7, 20,  1,
       14, 47, 31])

In [54]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [68]:
ranarr=np.random.randint(0,50,10)
ranarr

array([38, 47, 22, 48, 36, 34, 27, 33,  7, 11])

In [69]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
ranarr

array([38, 47, 22, 48, 36, 34, 27, 33,  7, 11])

In [73]:
max1=ranarr.max()
max1

48

In [75]:
min1=ranarr.min()
min1


7

In [79]:
#location of maxvalue
locmax1=ranarr.argmax()
locmax1

3

In [80]:
locmin1=ranarr.argmin()
locmin1

8

In [82]:
ranarr.shape

(10,)

In [85]:
arr.shape

(25,)

In [94]:
#to change shape of arr and assign to arr1
arr1=arr.reshape(5,5)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [90]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [92]:
arr1.shape

(5, 5)

In [93]:
#datatype
arr.dtype

dtype('int32')

In [106]:
print(np.random.randint(0,20))
#instead of calling like this we can import randint
from numpy.random import randint as ri1
print(ri1(0,20))

18
11
