In [4]:
import numpy as np

In [5]:
arr=np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr[5]

10

In [7]:
#slicing->indexing between two values
arr[1:5]

array([2, 4, 6, 8])

In [8]:
arr[:6]

array([ 0,  2,  4,  6,  8, 10])

In [9]:
arr[4:]

array([ 8, 10, 12, 14, 16, 18])

In [10]:
arr1=np.arange(0,30,3)
arr1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [11]:
#arr[start:stop]=value
arr1[0:5]=100

In [12]:
arr1

array([100, 100, 100, 100, 100,  15,  18,  21,  24,  27])

In [13]:
arr1

array([100, 100, 100, 100, 100,  15,  18,  21,  24,  27])

In [14]:
slice_of_arr1=arr1[0:5]
slice_of_arr1

array([100, 100, 100, 100, 100])

In [15]:
arr2=np.arange(0,20,2)
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
slice2=arr2[0:5]
slice2

array([0, 2, 4, 6, 8])

In [17]:
slice2[:]=99
slice2

array([99, 99, 99, 99, 99])

In [18]:
arr2

array([99, 99, 99, 99, 99, 10, 12, 14, 16, 18])

In [19]:
"""
when we do slice=arr2[0:5] we think we created a copy of arr2[0:5] elements to slice 
but it doesn't work like that

slice just act as a reference to arr2[0:5], ie if you make any change to slice it also effects arr[0:5]

so to creat copy we use copy method like below
"""


"\nwhen we do slice=arr2[0:5] we think we created a copy of arr2[0:5] elements to slice \nbut it doesn't work like that\n\nslice just act as a reference to arr2[0:5], ie if you make any change to slice it also effects arr[0:5]\n\nso to creat copy we use copy method like below\n"

In [20]:
arrcopy=arr2.copy()
arrcopy

array([99, 99, 99, 99, 99, 10, 12, 14, 16, 18])

In [21]:
arrcopy[:]=100
arrcopy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [22]:
arr2

array([99, 99, 99, 99, 99, 10, 12, 14, 16, 18])

In [23]:
#MATRIX INDEXING

In [24]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d[1][2]

30

In [26]:
#arr_2d[2][2]=arr_2d[2,2]
arr_2d[2,2]

45

In [27]:
"""
slicing inn 2d
arr_2d[rows which are needed(eg->0:1),columns which are needed(eg->1:2)]
"""
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [28]:
arr3=np.arange(0,11)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr3>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [30]:
arr4=np.arange(0,11)

In [31]:
arr4>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [32]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr4==5

array([False, False, False, False, False,  True, False, False, False,
       False, False])

In [34]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
bool_arr=arr4>5

In [36]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [37]:
arr4[bool_arr]

array([ 6,  7,  8,  9, 10])

In [38]:
arr5=np.random.randint(0,80,10)

In [39]:
arr5

array([ 3, 10, 69,  7,  5,  4, 75, 40, 10, 28])

In [41]:
bool_arr2=arr5>36
arr5[bool_arr2]

array([69, 75, 40])

In [42]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
arr5

array([ 3, 10, 69,  7,  5,  4, 75, 40, 10, 28])

In [45]:
arr5[arr>5]

array([ 7,  5,  4, 75, 40, 10, 28])

In [46]:
arr6=np.arange(50).reshape(5,10)

In [47]:
arr6

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [48]:
arr6[0:2,0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [49]:
arr6[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [51]:
#numpy operations

In [52]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
#array with array operations
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [54]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
#array with scalar operations
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [57]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [60]:
arr/0

C:\Users\kannoth\AppData\Local\Temp\ipykernel_14952\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0
C:\Users\kannoth\AppData\Local\Temp\ipykernel_14952\4291252909.py:1: RuntimeWarning: invalid value encountered in divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [61]:
arr/arr

C:\Users\kannoth\AppData\Local\Temp\ipykernel_14952\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
#numpy array gives warning ie. it goes to execute orgrm 

In [63]:
1/arr

C:\Users\kannoth\AppData\Local\Temp\ipykernel_14952\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [65]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [80]:
#array universal functions

In [67]:
np.sqrt(4)

2.0

In [68]:
np.sqrt(3)

1.7320508075688772

In [69]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [70]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [71]:
arr.max()

10

In [72]:
arr.min()

0

In [75]:
#arr.sin() ->wrong
#np.sin(arr) -> correct

In [76]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [77]:
np.log(arr)

C:\Users\kannoth\AppData\Local\Temp\ipykernel_14952\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [79]:
#-inf-> negative infinity