In [1]:
#kernerl trick

In [2]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from sklearn.datasets import load_breast_cancer

In [4]:
cancer=load_breast_cancer()

In [5]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [6]:
#print(cancer['DESCR'])
print(cancer['data_module'])



sklearn.datasets.data


In [7]:
df_feat=pd.DataFrame(data=cancer['data'],columns=cancer['feature_names'])

In [8]:
df_feat.head(2)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33            184.6   
1                 0.05667  ...         24.99          23.41            158.8   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  

[2 rows x 30 columns]

In [9]:
df_feat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X=df_feat
y=cancer['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [13]:
#support vector classifier model

In [14]:
from sklearn.svm import SVC

In [15]:
model=SVC()

In [16]:
model.fit(X_train,y_train)

SVC()

In [17]:
predictions=model.predict(X_test)

In [18]:
from sklearn.metrics import classification_report,confusion_matrix

In [19]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.95      0.85      0.90        66
           1       0.91      0.97      0.94       105

    accuracy                           0.92       171
   macro avg       0.93      0.91      0.92       171
weighted avg       0.93      0.92      0.92       171



In [20]:
print(confusion_matrix(y_test,predictions))

[[ 56  10]
 [  3 102]]


In [23]:
"""
in the tutorial video confusion matrix was kind of00,66,0,105]

as a reason it says we have to adjust parameters (model need to have parameters adjusted)
for that we use grid search to find best parameters

but in my notebook when id one i got confusion matrix of kind[56,10,3,102] (no 0 values)
when i enquired it in q&a forms ,it says it is due to updation of sklearn library
and thing what is got is correct since precision,recall and f-1 rate are having a good value

"""


'\nin the tutorial video confusion matrix was kind of00,66,0,105]\n\nas a reason it says we have to adjust parameters (model need to have parameters adjusted)\nfor that we use grid search to find best parameters\n\nbut in my notebook when id one i got confusion matrix of kind[56,10,3,102] (no 0 values)\nwhen i enquired it in q&a forms ,it says it is due to updation of sklearn library\nand thing what is got is correct since precision,recall and f-1 rate are having a good value\n\n'

In [22]:
"""
so for the tutorial purpose i am doing as the video says
i am performing grid search
"""

'\nso for the tutorial purpose i am doing as the video says\ni am performing grid search\n'

In [24]:
"""
Now a grid search allows you to find the right parameters such as like what C or gamma values to use

"""

'\nNow a grid search allows you to find the right parameters such as like what C or gamma values to use\n\n'

In [25]:
#grid search

In [26]:
from sklearn.model_selection import GridSearchCV

In [30]:
#here using gridsearchcv we change these parameteres of model
"""
we change these parameteres of model

class SVC(
    *,
    C: Float = 1,
    kernel: ((...) -> Any) | Literal['linear', 'poly', 'rbf', 'sigmoid', 'precomputed'] = "rbf",
    degree: Int = 3,
    gamma: float | Literal['scale', 'auto'] = "scale",
    coef0: Float = 0,
    shrinking: bool = True,
    probability: bool = False,
    tol: Float = 0.001,
    cache_size: Float = 200,
    class_weight: Mapping | str | None = None,
    verbose: bool = False,
    max_iter: Int = ...,
    decision_function_shape: Literal['ovo', 'ovr'] = "ovr",
    break_ties: bool = False,
    random_state: Int | RandomState | None = None
)

eg:
*A large C value gives you low bias and high variance low bias because you penalize the cost of misclassification
    with a smaller C value So it gives you a higher bias and a lower variance

*this gamma parameter is that free parameter in that radial basis function and not to go to mathematical
    technically speaking a large Gamla value is going to lead to a high bias and low variance in the

"""



'\nwe change these parameteres of model\n\nclass SVC(\n    *,\n    C: Float = 1,\n    kernel: ((...) -> Any) | Literal[\'linear\', \'poly\', \'rbf\', \'sigmoid\', \'precomputed\'] = "rbf",\n    degree: Int = 3,\n    gamma: float | Literal[\'scale\', \'auto\'] = "scale",\n    coef0: Float = 0,\n    shrinking: bool = True,\n    probability: bool = False,\n    tol: Float = 0.001,\n    cache_size: Float = 200,\n    class_weight: Mapping | str | None = None,\n    verbose: bool = False,\n    max_iter: Int = ...,\n    decision_function_shape: Literal[\'ovo\', \'ovr\'] = "ovr",\n    break_ties: bool = False,\n    random_state: Int | RandomState | None = None\n)\n'

In [31]:
param_grid={'C':[0.1,1,10,100,1000],'gamma':[1,0.1,0.01,0.001,0.0001]}

In [32]:
grid=GridSearchCV(SVC(),param_grid,verbose=3)

In [33]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ....................C=0.1, gamma=1;, score=0.637 total time=   0.0s
[CV 2/5] END ....................C=0.1, gamma=1;, score=0.637 total time=   0.0s
[CV 3/5] END ....................C=0.1, gamma=1;, score=0.625 total time=   0.0s
[CV 4/5] END ....................C=0.1, gamma=1;, score=0.633 total time=   0.0s
[CV 5/5] END ....................C=0.1, gamma=1;, score=0.633 total time=   0.0s
[CV 1/5] END ..................C=0.1, gamma=0.1;, score=0.637 total time=   0.0s
[CV 2/5] END ..................C=0.1, gamma=0.1;, score=0.637 total time=   0.0s
[CV 3/5] END ..................C=0.1, gamma=0.1;, score=0.625 total time=   0.0s
[CV 4/5] END ..................C=0.1, gamma=0.1;, score=0.633 total time=   0.0s
[CV 5/5] END ..................C=0.1, gamma=0.1;, score=0.633 total time=   0.0s
[CV 1/5] END .................C=0.1, gamma=0.01;, score=0.637 total time=   0.0s
[CV 2/5] END .................C=0.1, gamma=0.01

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
             verbose=3)

In [34]:
grid.best_params_

{'C': 1, 'gamma': 0.0001}

In [35]:
grid.best_estimator_

SVC(C=1, gamma=0.0001)

In [36]:
grid_predictions=grid.predict(X_test)

In [37]:
print(classification_report(y_test,grid_predictions))
print("\n")
print(confusion_matrix(y_test,grid_predictions))

              precision    recall  f1-score   support

           0       0.94      0.89      0.91        66
           1       0.94      0.96      0.95       105

    accuracy                           0.94       171
   macro avg       0.94      0.93      0.93       171
weighted avg       0.94      0.94      0.94       171



[[ 59   7]
 [  4 101]]


In [38]:
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test,predictions))

              precision    recall  f1-score   support

           0       0.95      0.85      0.90        66
           1       0.91      0.97      0.94       105

    accuracy                           0.92       171
   macro avg       0.93      0.91      0.92       171
weighted avg       0.93      0.92      0.92       171

[[ 56  10]
 [  3 102]]


In [ ]:
"""
in real life is set everything up.
Make sure your data is clean.

Go ahead and do a grid search on a very small set of grids just water to make sure that works correctly 
  and then once it does you'll set your full Paramo grade with as many default values as you want in yours
  As far as parameters you'll run your grid search and then you'll go to something else.
  
It'll depend on how fast your computer is as far as how long grid search will take to fully run.
"""
